import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Swal from "sweetalert2/dist/sweetalert2.js";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Online-Exams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-track-sky-700 scrollbar-thumb-sky-700`}
      >
        {children}
      </body>
    </html>
  );
}
